### ISSUE TITLE
Shading of dependencies

### ISSUE THREAD

**Issue by codepitbull** [PostHog/posthog-java#22]
We just added PostHog to some services for evaluation.

What struck us was that dependencies of PostHog aren't shaded.
We use OkHttp3 in several places but had to do some dependency-magic to actually get it working.

Tools like PostHog should be either free from dependencies or provide them shaded to avoid interference with the actual business code.

Would that be an option for you?
I could help if you consider this suggestion worthwhile ;)

Cheers,
Jochen

**Comment by timgl** [comment]
Hey Jochen,

If you'd want to raise a PR that'd be awesome!

**Comment by pauldambra** [comment]
was closed in #23
