### ISSUE TITLE
Support Groups

### ISSUE THREAD

**Issue by ericmeadows** [PostHog/posthog-java#26]
We are trying to use the product, and groups are not yet supported.  Please create parity with the other languages in terms of features.

**Comment by tiina303** [comment]
Workaround: you can use groups through providing `$groups { 'company': 'id5'}` like so in properties

**Comment by ericmeadows** [comment]
So something akin to the following, or does it need to be a string?
```java
HashMap<String, String> groups = new HashMap<String, String>() {
	{
		put("groupId", groupId);
	}
};
HashMap<String, Object> eventData = new HashMap<String, Object>() {
	{
		put("dataKey1", dataValue1);
		put("dataKey2", dataValue2);
		put("$groups", groups);
	}
};
```

**Comment by ericmeadows** [comment]
Another quick item in the documentation is that `id:5` does not let me know ahead of time if it will be `5`, or `id:5` in the stored data type.

**Comment by tiina303** [comment]
Yes that looks right. Let me know if it didn't work.
With "company" and "id:5" I was referring to the examples we use in the docs in other libraries (e.g.  https://posthog.com/docs/integrate/server/python#group-analytics)  - which is just a random name we picked to use, you could use names like "google", "meta" etc instead or whatever makes sense for your groups

**Comment by ericmeadows** [comment]
That worked.  It might be good to add that in the [documentation for Java](https://posthog.com/docs/integrate/server/java) because I thought groups was completely not supported.

**Comment by skydowx** [comment]
Is there a workaround to send group properties in Java?

**Comment by ivanagas** [comment]
This is now documented so closing 😄
