### ISSUE TITLE
support for feature flags

### ISSUE THREAD

**Issue by camerondeleone** [PostHog/posthog-java#28]
Add support for feature flags

**Comment by patimen** [comment]
When you say "support for feature flags", is that merely support in posthog-java for calling the decide API or full support with cached and in-memory feature flags for local evaluation?

**Comment by batosti** [comment]
I created a pull request with just the API calls

**Comment by pauldambra** [comment]
This will be covered when @marandaneto switches to kotlin based on Android SDK.
