### ISSUE TITLE
Verify retries work the way we want or update

### ISSUE THREAD

**Issue by tiina303** [PostHog/posthog-java#4]
okhttp has retries by default (https://square.github.io/okhttp/4.x/okhttp/okhttp3/-ok-http-client/-builder/retry-on-connection-failure/), but look into how they work, how many retries, is it with exponential backoff etc ...

**Comment by pauldambra** [comment]
at least initially fixed in #33 and any remainder can come when we move to the kotlin base code from Android SDK v3
