### ISSUE TITLE
Critical security dependencies in this lib

### ISSUE THREAD

**Issue by vongohren** [PostHog/posthog-java#46]
We are using owasp detection in our pipeline and this Lib pushes forward two issues. See images. I hope this can be adressed at some point

<img width="1691" alt="Screenshot 2023-11-03 at 11 57 27" src="https://github.com/PostHog/posthog-java/assets/1012055/525c3668-66b0-4a8f-8ada-cec3b815722a">
<img width="1728" alt="Screenshot 2023-11-03 at 11 57 17" src="https://github.com/PostHog/posthog-java/assets/1012055/73a86910-b61a-4809-a818-be22d7c36a9b">

**Comment by pauldambra** [comment]
Sorry to miss this!

We'll resolve this today
